### DISCUSSION TITLE
Running the DITA-OT on Github Actions

### DISCUSSION THREAD

**Discussion by stefan-jung** [dita-ot/dita-ot#4139] [Q&A] [answered]
I would like to use Github Actions to test DITA-OT plugins, create PDFs, and so forth. I have read [Running the dita command from a GitHub Action](https://www.dita-ot.org/dev/topics/using-github-actions.html), but think the custom actions don't work in my environment.

We have a private repository, which keeps a company specific version of the `dita-ot` with our plugins. It is basically a copy of the DITA-OT which is shipped with Oxygen XML, flavored with some other plugins. We are not permitted to use the Oxygen plugins on the CI server, so I try to throw them out during the job.

Now I am in the job of a DITA-OT plugin overriding `pdf2`. In the job, I clone the custom DITA-OT from my private repository (using a PAT). When calling the `dita install` command, I get an error message:

```
Failed to locate org.dita.dost.invoker.MainWithCPWildcarExpansion
```

I have no idea why. Can you help me with this problem, please? I paste the  job file below.

![image](https://user-images.githubusercontent.com/3266567/222739208-58ec3f24-c53b-4edb-a3dc-42730ec7fd9b.png)

```yaml
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  DITA_OT_VERSION: 3.6.1
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
            
      - name: ZIP plugin 
        run: zip -qq -r com.dometic.dita-ot-pdf.zip .
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Checkout DITA-OT 🍌
        uses: actions/checkout@v3
        with:
          repository: onedometic/dita-ot
          path: ./dita-ot
          token: ${{ secrets.GH_PAT }}
        
      - name: Grant execute permissions for dita
        run: chmod +x dita-ot/bin/dita
        
      - name: Grant execute permissions for ant
        run: chmod +x dita-ot/bin/ant
        
      - name: DITA-OT Version
        run: dita-ot/bin/dita --version
        
      - name: Remove plugins ☣
        run: |
          rm -rf dita-ot/plugins/com.oxygenxml.common
          rm -rf dita-ot/plugins/com.oxygenxml.dita.metrics.report
          rm -rf dita-ot/plugins/com.oxygenxml.dost.patches
          rm -rf dita-ot/plugins/com.oxygenxml.editlink
          rm -rf dita-ot/plugins/com.oxygenxml.export.map
          rm -rf dita-ot/plugins/com.oxygenxml.highlight
          rm -rf dita-ot/plugins/com.oxygenxml.html.embed
          rm -rf dita-ot/plugins/com.oxygenxml.image.float
          rm -rf dita-ot/plugins/com.oxygenxml.media
          rm -rf dita-ot/plugins/com.oxygenxml.merged
          rm -rf dita-ot/plugins/com.oxygenxml.pdf.css
          rm -rf dita-ot/plugins/com.oxygenxml.pdf.custom
          rm -rf dita-ot/plugins/com.oxygenxml.pdf.review
          rm -rf dita-ot/plugins/com.oxygenxml.webhelp.common
          rm -rf dita-ot/plugins/com.oxygenxml.webhelp.responsive
          dita-ot/bin/dita install
```
