### DISCUSSION TITLE
GitHub Actions should fail on error, but it does not

### DISCUSSION THREAD

**Discussion by stefan-jung** [dita-ot/dita-ot#4286] [Q&A] [answered]
Hi community,

I would like GitHub Action to fail, if there is an error and break the build. I'm publishing with DITA-OT project files. When I build with Oxygen XML, Oxygen XML crashes on my project with a DOTJ012F (because my test file contains invalid grammar), which is correct and expected. But GitHub Actions just overflows the warnings and errors and does not fail the build. I've set `--processing-mode=strict` and don't know what else I can do. Any ideas?

This is the relevant section of the GitHub Action YAML file:

```yaml
      # Install all plugins and build the test files
      - name: 🚀 Build PDF using DITA-OT 3.7.4
        uses: dita-ot/dita-ot-action@master
        with:
          dita-ot-version: 3.7.4

          install : |
            dita install com.dometic.dita-doctypes.zip --force
            dita install com.dometic.dita-technical-data.zip --force
            dita install https://github.com/dita-community/org.dita-community.split-page-sequences/archive/refs/heads/develop.zip --force
            dita install com.dometic.dita-ot-pdf.zip --force
          build: |
            dita --project=test-files/test-files.xml --processing-mode=strict --verbose
```

Any ideas?
