### DISCUSSION TITLE
PDF Not Being Generated When Running DITA-OT Docker Container in GitHub Actions Workflow

### DISCUSSION THREAD

**Discussion by IbrahimBhatty-Emumba** [dita-ot/dita-ot#4477] [Q&A] [answered]
In my GitHub Actions workflow, I'm attempting to generate PDF files using a Docker container with DITA-OT. While the workflow runs without errors, the PDF files are not being generated as expected, and the logs are also empty. Here's a detailed description of the issue:

Despite configuring the GitHub Actions workflow to run a Docker container with DITA-OT for PDF generation, the PDF files are not being generated. After the workflow execution, the out directory, where the PDF files are supposed to be stored, remains empty. Additionally, the logs generated by the workflow do not contain any error messages or indications of the PDF generation process.

This is my workflow file:

```yaml
name: CI
'on':
  push:
    branches:
      - master
      - main
jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    steps:

      # - name: Install JDK 11
      #   run: sudo apt-get install -y openjdk-11-jdk

      # - name: Install JDK 8 Development Package
      #   run: sudo apt-get install -y openjdk-8-jdk openjdk-8-jdk-headless

      # - name: Set Java 8 as Default
      #   run: sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

      - name: Git checkout
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -al

      # - name: Build PDF
      #   uses: dita-ot/dita-ot-action@master
      #   with:
      #     input: sequence.ditamap
      #     transtype: pdf
      #     output-path: out

      # - name: Build PDF using DITA-OT 3.5.4
      #   uses: dita-ot/dita-ot-action@master
      #   with:
      #       dita-ot-version: 3.5.4
      #       input: 'sequence.ditamap'
      #       transtype: 'pdf'
      #       properties: '--filter=pdf.ditaval'
      #       output-path: .
      - name: Build PDF using DITA-OT Docker image
        run: docker run --rm -v ${{ github.workspace }}:/workspace ditaot/dita-ot:latest dita --input=/workspace/sequence.ditamap --format=pdf2 -o /workspace
      
      # - name: Display log
      #   run: cat dita_output.log

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: generated-pdf
          path: out/*.pdf

```

I have tried to troubleshoot this to the best of my ability but to no avail. Do let me know if you need any other details that could help in identifying the issue. 

Thank you for your assistance and expertise!
