### ISSUE TITLE
Question: Adding GitHub Actions. DITA-OT as a static website generator?

### ISSUE THREAD

**Issue by jason-fox** [dita-ot/dita-ot#3664]
I have been transfering my CI from Travis to GitHub Actions and I created a [GitHub Action for the unit-test plugin](https://github.com/jason-fox/dita-unit-test-action) for the DITA-OT plugin unit test framework. You can see a sample run [here](https://github.com/jason-fox/fox.jason.translate.xliff/runs/1618598953?check_suite_focus=true).

Obviously with the specific Unit Test GitHub Action based on my own `fox.jason.unit-test` plugin, it makes sense to be hosted  within my own `jason-fox` GitHub, but I have also created a more generic version to run any `dita` command. This repo currently hosts the generic DITA-OT GitHub Action: https://github.com/jason-fox/dita-build-action

![action](https://user-images.githubusercontent.com/3439249/103441576-3d546300-4c4f-11eb-9692-b5528c457c59.png)

The `README` in the repo already follows the Standard GitHub Action format and describes proper usage.

### Example in action

This -  https://github.com/jason-fox/test-dita-build - is a sample repository which uses the action on a test run:  it includes a few extra plugins and prerequisites to show what can be done - it builds a PDF and a custom HTML build. It combines with other actions to create a static website.

The outputs are fully customizable, but in this case it is a PDF document [here](https://jason-fox.github.io/test-dita-build/pdf/document.pdf) and an HTML website [here](https://jason-fox.github.io/test-dita-build/html5-bootstrap/topics/examples.html)

### Questions:

1) Before I add this generic DITA-OT Action to the GitHub Actions marketplace myself, I was wondering should it be transfered to be hosted under the `dita-ot` organization?

2) Regardless of whether the `dita-ot` organization wants to host this code or not,  what sort of documentation would you like added to the docs to support this?

**Comment by jelovirt** [comment]
This is something we probably should do under the dita-ot organization. So 👍🏽 there. However, the actual implementation here is not IMO ready yet for public consumption.

The API right now not that user friendly. The example in the README is

```yaml
dita-ot-version: 3.6
setup-script: 'startup.sh'
prerequisites: 'org.doctales.xmltask,fox.jason.extend.css,fox.jason.prismjs'
ditamap: 'docsrc/document.ditamap'
transtypes: 'html5,pdf'
properties: '--filter=filter1.ditaval' # Any additional command line properties
output-dir: 'out' # The folder the action should write to.
```

IMO it should be more like

```yaml
dita-ot-version: '3.6'
# remove setup-script, we don't need to support this. Users who need it can handle this in their GA config
# prerequisites: this should be an array and the name should be something like plugins:
plugins:
- 'org.doctales.xmltask'
- 'fox.jason.extend.css
- 'fox.jason.prismjs'
# ditamap: this should be input, because the start file can also be a topic
input: 'docsrc/document.ditamap'
# this should only support one transtype, users can run multiple transtypes in their GA config
transtypes: 'html5'
# properties: this should not be list of CLI argument, but rather actual YAML key-value pairs
properties:
  filter: 'filter1.ditaval'
output-dir: 'out'
```

The other problem I see is in the implementation. Right now it's a Docker image that simply calls a shell script. The shell script then downloads DITA-OT with curl _every time it's run_. The implementation should use a Docker image that already has a given DITA-OT installed and you choose the DITA-OT version with different versions of the Action. This way we don't waste bandwidth by redownloading the distribution packages every time.

**Comment by infotexture** [comment]
@jason-fox Thanks for the initiative, a GitHub Action that runs DITA-OT would be useful indeed. 🙏 

Perhaps the Action could be refactored to build on our [existing Docker image](https://github.com/dita-ot/dita-ot/packages/24860) instead of downloading via `curl`?

**Comment by jason-fox** [comment]
> Perhaps the Action could be refactored to build on our existing Docker image instead of downloading via curl?

That image pushes to the old GitHub Packages Docker registry (`docker.pkg.github.com`). Could someone push to the newer  GitHub Container Registry (`ghcr.io`), that will allow users external to the `dita-ot` organization to access the packages to be publicly accessible without any authentication. Note that new images are private by default, so after the first push you’d need to switch the image to public manually.

What is more likely to work is that the Build Action Docker image will use 

```Dockerfile
FROM ghcr.io/dita-ot/dita-ot/dita-ot:3.6
```

 as the base image. Any chance someone could flip that switch and make it public so I no longer need to `curl`?

> The API right now not that user friendly. 

The API is just the one from the Unit Test Action - I can easily amend the following:

```yaml
# ditamap: this should be input, because the start file can also be a topic
input: 'docsrc/document.ditamap'
# this should only support one transtype, users can run multiple transtypes in their GA config
transtypes: 'html5'
```

These are trickier - the current Docker container GitHub Action only accepts strings:

```yaml
# prerequisites: this should be an array and the name should be something like plugins:
plugins:
- 'org.doctales.xmltask'
- 'fox.jason.extend.css
- 'fox.jason.prismjs'
# properties: this should not be list of CLI argument, but rather actual YAML key-value pairs
properties:
  filter: 'filter1.ditaval'
```

**Comment by jason-fox** [comment]
I have updated the GitHub Action interface to be much more flexible e.g:

### Build using command line statements only (`install` and `build`)

```yaml
- name: Build Using Command Line
  uses: jason-fox/dita-build-action@master
  with:
      install : |
        export DEBIAN_FRONTEND=noninteractive
        ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
        dpkg-reconfigure --frontend noninteractive locales tzdata
        locale-gen en_US.UTF-8
        dita install fox.jason.extend.css
        dita install org.doctales.xmltask
        dita install fox.jason.prismjs
      build: |
        dita -i document.ditamap -o out  -f pdf --filter=filter1.ditaval
```

## Build using parameters only (`plugins`, `input`, `output-path` etc.)

```yaml
- name: Build PDF 
  uses: jason-fox/dita-build-action@master
  with:
      plugins: |
        org.doctales.xmltask
        fox.jason.extend.css
        fox.jason.prismjs
      input: 'docsrc/document.ditamap'
      transtype: 'pdf'
      properties: '--filter=filter1.ditaval'
      output-path: out
```

The  `dita-ot-version` parameter should not be required (it defaults to the DITA-OT of the parent version) but if present will revert to an different DITA-OT build.

I assume that eventually proper versioning of the GitHub Action will align with the DITA-OT build anyway:

```yaml
- name: Build PDF 
  uses: jason-fox/dita-build-action@3.6
```

All parameters are Docker ENV strings, but the underlying scripts can split params using comma or line separators so the list of `plugins` or `properties` can be placed on separate lines for ease of reading.
