### ISSUE TITLE
Docker build failed in dita-ot-action

### ISSUE THREAD

**Issue by wangjie-agora** [dita-ot/dita-ot#3725]
## Expected Behavior
Docker build should pass.

## Actual Behavior
Docker build failed at step 8.

## Copy of the error message, log file or stack trace

```
Step 8/12 : RUN export DEBIAN_FRONTEND=noninteractive && 	ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime &&     dpkg-reconfigure --frontend noninteractive locales tzdata && 	locale-gen en_US.UTF-8 &&     rm -rf /var/lib/apt/lists/* &&     chmod +x /entrypoint.sh && 	chmod +x /build_script.sh  && 	chmod +x /install_script.sh
139
   ---> Running in 6d94f3852fe7
140
  Generating locales (this might take a while)...
141
    en_US.UTF-8... done
142
  Generation complete.
143
  dpkg-query: package 'tzdata' is not installed and no information is available
144
  Use dpkg --info (= dpkg-deb --info) to examine archive files,
145
  and dpkg --contents (= dpkg-deb --contents) to list their contents.
146
  /usr/sbin/dpkg-reconfigure: tzdata is not installed
147
  The command '/bin/bash -o pipefail -c export DEBIAN_FRONTEND=noninteractive && 	ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime &&     dpkg-reconfigure --frontend noninteractive locales tzdata && 	locale-gen en_US.UTF-8 &&     rm -rf /var/lib/apt/lists/* &&     chmod +x /entrypoint.sh && 	chmod +x /build_script.sh  && 	chmod +x /install_script.sh' returned a non-zero code: 1
```

## Environment
 The action yaml code:

```yaml
name: CI
'on':
  push:
    branches:
      - gh-actions
jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Build HTML
        uses: dita-ot/dita-ot-action@master
        with:
          input: cn/RTC/RTC_API_Windows.ditamap
          transtype: html5
          output-path: out
```
