### ISSUE TITLE
Improve project files in YAML

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#4047]
## Description
Improve YAML project files to use more idiomatic structures.

## Possible Solution
Instead of the current:

```yaml
params:
  - name: 'args.copycss'
    value: 'yes'
  - name: 'args.cssroot'
    path: '../../resources'
```
Also support shorted
```yaml
params:
  args.copycss: yes
  args.cssroot:
    type: path
    value: '../../resources/header.xml'
```
Or

Also support shorted
```yaml
params:
  args.cssroot:
    path: '../../resources/header.xml'
```
